### ISSUE TITLE
Subtraction

### ISSUE THREAD

**Issue by Cryoris** [Cryoris/qiskit-terra#25]
Add a circuit for subtraction. Subtraction is essentially addition but the argument we subtract is replaced by it's two's complement. That can be achieved by first flipping all bits and then adding the integer 1 to it. E.g.
```
y = 011 (initially 3)
-> 100 (flipping all bits)
-> 101 (adding 1) 
```
and the two's complement of 3 is indeed 101.

**Comment by ManjulaGandhi** [comment]
Interested to work on this @Cryoris
