### ISSUE TITLE
Simple adder circuits

### ISSUE THREAD

**Issue by Cryoris** [Cryoris/qiskit-terra#5]
### Summary

Add simple adder circuits.

### Details

Implement the following two versions of adder circuits including unit tests.
- [x] Ripple-carry adder: https://arxiv.org/pdf/quant-ph/0410184.pdf
- [ ] Out-of-place/reversible adder: https://arxiv.org/pdf/quant-ph/0008033.pdf
- [ ] QFT-based adder: https://arxiv.org/pdf/quant-ph/0008033.pdf

These two circuits should have the same interface so they can be used interchangeably, e.g.
```python
adder1 = RippleCarryAdder(num_qubits_a, num_qubits_b)
adder2 = QFTAdder(num_qubits_a, num_qubits_b)
```

**Comment by mantcep** [comment]
Hey @Cryoris, I would like to start with ripple-carry adder using the given reference, if that's fine :)

**Comment by ManjulaGandhi** [comment]
Hi @Cryoris, I am unable to work with BCD adder, so shall I work on QFT-based adder.

**Comment by Cryoris** [comment]
Yes @ManjulaGandhi, that's a good idea 🙂
